import { Button } from "@/components/ui/button";
import { Download, Package } from "lucide-react";
import { downloadElementAsPDF } from "@/lib/resourceUtils";
import { exitTicketData } from "@/data/exitTicketMegaPack";

const sectionColors: Record<string, string> = {
  Math: "bg-primary/10 text-primary border-primary/20",
  ELA: "bg-secondary/10 text-secondary border-secondary/20",
  Science: "bg-accent/20 text-accent-foreground border-accent/20",
  "Social Studies": "bg-muted text-muted-foreground border-border",
};

const ExitTicketMegaPack = () => {
  const handleDownload = () => downloadElementAsPDF("mega-pack-output", "Exit-Ticket-Mega-Pack-Grades-3-5");

  return (
    <div className="mx-auto max-w-4xl">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="font-display text-2xl font-bold text-foreground">Exit Ticket Mega Pack</h1>
          <p className="text-muted-foreground">100 ready-to-print exit tickets for Grades 3–5</p>
        </div>
        <Button onClick={handleDownload} className="rounded-xl">
          <Download className="mr-2 h-4 w-4" /> Download PDF
        </Button>
      </div>

      <div id="mega-pack-output" className="space-y-0 rounded-2xl border bg-card">
        {/* Cover Page */}
        <div className="flex min-h-[600px] flex-col items-center justify-center border-b border-border p-12 text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-primary/10 px-5 py-2 text-sm font-semibold uppercase tracking-wider text-primary">
            <Package className="h-4 w-4" /> Mega Pack
          </div>
          <h2 className="font-display text-4xl font-extrabold text-foreground leading-tight md:text-5xl">
            100 Exit Tickets
          </h2>
          <p className="mt-3 text-xl text-muted-foreground">for Grades 3–5</p>
          <div className="mx-auto mt-8 grid max-w-md grid-cols-2 gap-3 text-sm">
            {["Math", "ELA", "Science", "Social Studies"].map((s) => (
              <span key={s} className={`rounded-lg border px-4 py-2 font-medium ${sectionColors[s]}`}>{s}</span>
            ))}
          </div>
          <div className="mt-10 space-y-1 text-sm text-muted-foreground">
            <p>📚 Simple comprehension • Short response • Critical thinking</p>
            <p>🖨️ Ready to print &nbsp;•&nbsp; Student-friendly language</p>
          </div>
        </div>

        {/* Questions by Subject */}
        {exitTicketData.map((section, si) => (
          <div key={section.subject} className={`p-8 ${si < exitTicketData.length - 1 ? "border-b border-border" : ""}`}>
            <div className="mb-6 flex items-center gap-3">
              <span className={`inline-flex rounded-lg border px-4 py-1.5 text-sm font-bold uppercase tracking-wider ${sectionColors[section.subject]}`}>
                {section.subject}
              </span>
              <span className="text-sm text-muted-foreground">{section.questions.length} questions</span>
            </div>

            <div className="space-y-5">
              {section.questions.map((q, qi) => (
                <div key={qi} className="rounded-xl border border-border p-5 space-y-3">
                  <div className="flex items-center gap-3">
                    <span className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">
                      {q.globalNumber}
                    </span>
                    <span className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${
                      q.type === "comprehension" ? "bg-primary/10 text-primary" :
                      q.type === "short_response" ? "bg-secondary/10 text-secondary" :
                      "bg-accent/20 text-accent-foreground"
                    }`}>
                      {q.typeLabel}
                    </span>
                  </div>
                  <p className="text-sm font-medium text-foreground leading-relaxed">{q.question}</p>
                  <div className="space-y-2 pt-1">
                    {Array.from({ length: q.lines }).map((_, i) => (
                      <div key={i} className="h-6 border-b border-muted-foreground/20" />
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}

        {/* Footer */}
        <div className="border-t border-border p-6 text-center">
          <p className="text-xs text-muted-foreground italic">
            ✅ Exit Ticket Mega Pack — 100 Questions for Grades 3–5 — Generated by TeachKit
          </p>
        </div>
      </div>
    </div>
  );
};

export default ExitTicketMegaPack;
